version: '3.4'

services:
  cloudfilestorage:
    image: ${DOCKER_REGISTRY-}cloudfilestorage
    container_name: cloudfilestorage
    build:
      context: .
      dockerfile: CloudFileStorage/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  cloudfilestorage.database:
    image: postgres:16.1
    container_name: cloudfilestorage.database
    environment: 
        - POSTGRES_DB=cloudfilestorage
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1234
        #- PGDATA=/tmp
    volumes:
        - pgdata:/var/lib/postgresql/data
    ports:
        - 5432:5432

volumes:
  pgdata:

